### ISSUE TITLE
mlpack 4.0 compatibility

### ISSUE THREAD

**Issue by mh415-f** [fslivovsky/pedant-solver#1]
Hello, first I'd like to thank you for making pedant-solver public!

I want to compile pedant-solver with mlpack version 4.0, but when running CMake, I see the following among the logs:
`-- Could NOT find MLPACK (missing: MLPACK_LIBRARY) (found version "4.0.0")`
Is pedant-solver not meant to be compiled with mlpack 4.0? If it's possible, I'd be happy if you could provide an update which enables compilation with mlpack 4.0.

Thank you and best regards

**Comment by fxreichl** [comment]
Hello,
to use mlpack 4 you can use the attached patch. While the new version of mlpack should work fine with pedant, we have not yet tested it. For this reason we will not update the repository for now. If you encounter any problems with mlpack 4 we would be happy if you could report them.
Best regards,
Franz

[mlpack4.txt](https://github.com/fslivovsky/pedant-solver/files/10019841/mlpack4.txt)

**Comment by mh415-f** [comment]
Hello Franz,
sorry for the late reply and thank you a lot for providing the patch!
Looking at the results I get on the QBFEVAL DQBF instances, I'd say everything works fine so far.
I'd inform you in case problems occur later on.
